version: 0.2

phases:
  install:
    commands:
      - pip install awscli
  build:
    commands:
      - aws s3 cp index.html s3://luit-blue-may-2024-cicd-beta --acl public-read
      - if [ "$CODEBUILD_WEBHOOK_EVENT" == "PULL_REQUEST_MERGED" ]; then aws s3 cp index.html s3://luit-blue-may-2024-cicd-prod --acl public-read; fi
